version: '3.4'

services:
  lokpie.engine.docker.linux:
    image: lokpie-engine-docker-linux
    container_name: lokpie
    build:
      context: .
      dockerfile: Lokpie.Engine.Docker.Linux/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
      - orm__connection__connectionString=Server=;Database=;User ID=;Password=
      - masstransit__masstransitConfiguration__baseUrl=
    ports:
      - "5000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "*"
